[default]
SECRET_KEY="@jinja {{env.SECRET_KEY}}"
PICPAY_TOKEN="@jinja {{env.PICPAY_TOKEN}}"
SQLALCHEMY_TRACK_MODIFICATIONS=false

MAIL_SENDER="@jinja {{env.MAIL_SENDER}}"
MAIL_SERVER="@jinja {{env.MAIL_SERVER}}"
MAIL_PORT="@jinja {{env.MAIL_PORT}}"
MAIL_USERNAME="@jinja {{env.MAIL_USERNAME}}"
MAIL_PASSWORD="@jinja {{env.MAIL_PASSWORD}}"
MAIL_USE_TLS=false
MAIL_USE_SSL=true

[development]
SQLALCHEMY_DATABASE_URI="@jinja {{env.DATABASE_DEV_URI}}"
PICPAY_CALLBACK_URL="http://localhost:5000/meus-pedidos"
PICPAY_RETURN_URL="http://localhost:5000/order/notification"

[production]
SQLALCHEMY_DATABASE_URI="@jinja {{env.DATABASE_URI}}"
PICPAY_CALLBACK_URL="http://www.sualoja.com.br/callback"
PICPAY_RETURN_URL="http://www.sualoja.com.br/cliente/pedido/102030"

[testing]
SQLALCHEMY_DATABASE_URI="sqlite://"