"""empty message

Revision ID: 85c12da3dd64
Revises: 67972288f30f
Create Date: 2021-02-04 12:12:57.246610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85c12da3dd64'
down_revision = '67972288f30f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('document', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_document'), 'profiles', ['document'], unique=True)
    op.create_index(op.f('ix_profiles_phone'), 'profiles', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_phone'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_document'), table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
