"""empty message

Revision ID: b072344d5d2c
Revises: 1ca16aea12c6
Create Date: 2021-02-04 08:37:54.228929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b072344d5d2c'
down_revision = '1ca16aea12c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('products', 'created_at')
    op.drop_column('categories', 'created_at')
    # ### end Alembic commands ###
